### ISSUE TITLE
coding bug found

### ISSUE THREAD

**Issue by mcl-uk** [rppicomidi/pico-usb-host-msc-demo#2]
FYI The if statement at line 153 in pico-usb-host-msc-demo.c can never execute, it is preceeded by a return

**Comment by rppicomidi** [comment]
@mcl-uk Thanks for the bug report. Code looks very wrong there. Will try to address it soon.

**Comment by rppicomidi** [comment]
@mcl-uk Pushed a fix. Thank you for finding that.

**Comment by mcl-uk** [comment]
No worries, thanks for the fix. BTW do you have any prospect of improving the current 64kB/s MSC transfer speed limitation, independant of HaThatch who has no time?

**Comment by rppicomidi** [comment]
@mcl-uk Steve. Sorry, no. The slow USB Bulk transfer rate is fine for my projects right now. The files my projects deal with are few and small, and MIDI, which also uses bulk transfer, maxes out at 16 simultaneous streams at 3.125 kbytes/second, which only requires 50 kbytes/second. I am also not convinced the hardware is capable of going a lot faster because the only other way to drive the USB host is by software managing the transfers one packet at a time.

**Comment by rppicomidi** [comment]
@mcl-uk For what it's worth, I just pushed a pio-usb branch to this project. The code in that branch supports a second USB port
crafted from PIO modules instead of the native USB hardware. I can't say whether it is faster or slower or about the same speed as using the native hardware. I find it useful when I need both a USB device and USB host at the same time.
